[package]
name = "windows_tools"
version = "0.1.0"
edition = "2021"
authors = ["Jagoba Inda Arizaleta"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
